# Generated by Django 5.0.3 on 2024-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registermodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=300)),
                ("lasttname", models.CharField(max_length=300)),
                ("userid", models.CharField(max_length=300)),
                ("password", models.IntegerField()),
                ("mblenum", models.BigIntegerField()),
                ("email", models.EmailField(max_length=400, null=True)),
            ],
        ),
    ]
