# Generated by Django 5.0.3 on 2024-03-14 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_detail", "0003_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.BigIntegerField()),
                ("Email", models.CharField(max_length=300)),
                ("Account", models.CharField(max_length=300)),
                ("Benificary_Name", models.CharField(max_length=300)),
                ("created_by", models.IntegerField()),
                ("created_date", models.DateField(default=datetime.datetime.now)),
                ("updated_by", models.IntegerField()),
                ("updated_date", models.DateField(default=datetime.datetime.now)),
                ("status", models.SmallIntegerField(default=1)),
            ],
        ),
    ]
